### ISSUE TITLE
 Any way to override base URL?

### ISSUE THREAD

**Issue by EmilZhou** [ThinkGeo/VectorMap-js#1]
Hi Guys,

Do you know if there is a way to override the base tile request URL when using our VectorMap JS library?  Right now it appears that all tile requests are made to a base URL of https://cloud[x].thinkgeo.com (where [x] is a random number from 1-6).  I’m wondering if there is a parameter that can be set in user code which overrides this, e.g. to point to our test environment or localhost for example.

Thanks,

**Comment by Johnny-Zhangzhao** [comment]
Hi, 

please pull the latest version of 2.0.2 which provides 3 options as below.

1. Give it in StyleJson file  where configure the style, data sources etc.

<code lang="js">
"sources": [
            {
                "id": "worldstreets_source",
                "urls": [
                    "https://cloud1.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
                    "https://cloud2.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
                    "https://cloud3.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
                    "https://cloud4.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
                    "https://cloud5.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
                    "https://cloud6.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf"
                ],
                "type": "MVT"
            }
        ]

</code>


2. Assign it when create the instance of ol.mapsuite.VectorTileLayer, code like below

<code lang="js">
let layer = new ol.mapsuite.VectorTileLayer(lightStyleJson, {
    apiKey: "***",
    urls: [
        "https://cloud1.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
        "https://cloud2.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
        "https://cloud3.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
        "https://cloud4.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
        "https://cloud5.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
        "https://cloud6.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf"
    ]
});

</code>


3.  Change it with function "setUrls"

<code lang="js">
let layer = new ol.mapsuite.VectorTileLayer(lightStyleJson, {
    apiKey: "***"
});
layer.setUrls([
    "https://cloud1.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
    "https://cloud2.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
    "https://cloud3.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
    "https://cloud4.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
    "https://cloud5.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf",
    "https://cloud6.thinkgeo.com/api/v1/maps/vector/streets/3857/{z}/{x}/{y}.pbf"
]);

</code>

Thanks,
Johnny

**Comment by Johnny-Zhangzhao** [comment]
Fixed and can be available in v2.0.2
